# /manifest-services.yml
services:
  infrastructure.mongodb:
    class: '../services/MongoManager'
    calls: [{ method: 'run' }]

  # repositorios
  repository.user:
    class: '../repository/UserRepository'
    arguments: ['@infrastructure.mongodb']
        
  # servicios
  service.user-authenticator:
    class: '../services/UserAuthenticator'
    arguments: ['@repository.user']

  service.user-creator:
    class: '../services/UserCreator'
    arguments: ['@repository.user']
  
  service.user-data-updater:
    class: '../services/UserDataUpdater'
    arguments: ['@repository.user']

  service.user-password-updater:
    class: '../services/UserPasswordUpdater'
    arguments: ['@repository.user']